---
app-menu:
  description: The hamburger menu
  hasExposure: true
  exposureDescription: ""
  variables:
    menu-items:
      type: json
      description: The menu items in an unsorted object
messaging:
  description: "Configuration for the messaging system.\nIn practice this is a set of growable lookup tables for the message controller to piece together.\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    actions:
      type: json
      description: A growable map of action URLs.
    message-under-experiment:
      type: string
      description: Id or prefix of the message under experiment.
    messages:
      type: json
      description: "A growable collection of messages, where the Key is the message identifier and the value is its associated MessageData."
    on-control:
      type: string
      description: What should be displayed when a control message is selected.
      enum:
        - show-next-message
        - show-none
    styles:
      type: json
      description: "A map of styles to configure message appearance.\n"
    triggers:
      type: json
      description: "A collection of out the box trigger expressions. Each entry maps to a valid JEXL expression.\n"
onboarding:
  description: "The onboarding experience, split into several pages."
  hasExposure: true
  exposureDescription: ""
  variables:
    page-order:
      type: json
      description: The explicit order to display the pages.
    pages:
      type: json
      description: Each screen of the onboarding flow
